### ISSUE TITLE
Synchronizing Runnables

### ISSUE THREAD

**Issue by katipogluMustafa** [CagdasAyyildiz/JavaPractice#1]
The run methods in the code looks like unnecessarily used synchronized keyword?

Have you tried to make runnables work in parallel? , it seems like it will always have sequential execution in this form?

**Comment by CagdasAyyildiz** [comment]
I thought it was neccesary at first. I'll fix it. Thanks.

**Comment by katipogluMustafa** [comment]
#2 Fixes the solution
